### ISSUE TITLE
Editor fails to load any template (error from  https://bee-bumper.getbee.io/v2/bump)

### ISSUE THREAD

**Issue by danielickes** [BeefreeSDK/beefree-sdk-npm-official#135]
Up until now we've used the Bee SDK and it worked just fine but at the moment we're getting following error when we try to load any template into the editor: 
```
code : 2200
message : "cannot decode json value of type string into field that is type bumper.extraFields"
status_code : 400
```

The behavior can be reproduced in both Page and Email editor. We initialize the editor in the following way:

```
async initBee(beeConfig: any, token: BeeToken) {
        this.beeInstance = new BeePlugin({ access_token: token.beeToken, v2: true, status: TokenStatus.OK });
        await this.beeInstance
            .start(beeConfig, this.assetJson, "", { shared: false })
            .then(() => {
                this.pluginLoading = false;
                this.isInitialized = true;
            });
    }

```

We didn't change anything on our side. Also setting the parameter v2 to false doesn't change anything (the request is still going to 
https://bee-bumper.getbee.io/v2/bump)

Here some screenshots:

![Screenshot 2024-02-01 152757](https://github.com/BeefreeSDK/beefree-sdk-npm-official/assets/104588060/457f310f-dac6-408d-9eb8-1baa39aa9bad)
![Screenshot 2024-02-01 152823](https://github.com/BeefreeSDK/beefree-sdk-npm-official/assets/104588060/911d64fa-7aba-48b3-ae27-72534f49ca28)

![image](https://github.com/BeefreeSDK/beefree-sdk-npm-official/assets/104588060/e8b0f7a3-bf83-4074-b113-b0bdfb76e193)

**Comment by pinkynrg** [comment]
@DanielIckes, the solution has been implemented. Please attempt to save the message again; the issue should resolve itself.

**Comment by danielickes** [comment]
@pinkynrg can confirm that it's working now. Thank you.
