### ISSUE TITLE
rowDisplayConditions is missing as a type in ContentDialog

### ISSUE THREAD

**Issue by cruzayye** [BeefreeSDK/beefree-sdk-npm-official#139]
**Describe the bug**
in the npm version of this plugin, the rowDisplayConditions is not part of the contentDialog type.
**To Reproduce**
1. download the npm version of the beeEditor
2. Try to insert the following as part of contentDialog in the BeeConfigs
`	rowDisplayConditions: {
		label: 'Custom text for display conditions',
		handler: function(resolve, reject) {
			// Your function
		}
	},`

3. You get a TS error saying that this is not part of ContentDialog even though the docs showcase it
https://docs.beefree.io/beefree-sdk/advanced-options/content-dialog#how-it-works

![Screenshot 2024-02-23 at 2 04 29 PM (2)](https://github.com/BeefreeSDK/beefree-sdk-npm-official/assets/40680065/693af877-a27b-4a09-81e0-f4126ab4c591)

**Comment by mattweberio** [comment]
Hi @cruzayye - We have an internal Jira task open for this item and we'll post back here once it's released.
